#+TITLE: Tracey's Introduction to Linux and Programming
#+AUTHOR: Christian Johnson
#+OPTIONS: toc:2
#+begin_export latex
\newpage
#+end_export

* Lesson 1 - Introduction to Linux
Linux is an open-source operating system kernel initially developed by Linus Torvalds in 1991. It is the foundation of numerous operating systems known as Linux distributions.

This section will introduce you to some high level concepts that are important to understanding what Linux is.

** Kernels
A kernel is the core component of an operating system. It manages system resources, such as CPU, memory, and peripherals, and provides services for applications. It acts as a bridge between software and hardware. It is not necessary to understand how a kernel works, it's simply important to recognize that the kernel exists to translate code and software instructions to hardware. 

Linux itself if /not/ an operating system - it is only a [[*Kernels][Kernel]]. The operating system commonly referred to as "Linux" should actually be called "GNU + Linux". GNU here refers to a collection of open source tools and programs that work with the Linux kernel to create a functioning operating system. That is what all operating systems that are considered part of the "Linux" family /are/ - the Linux kernel packaged with a collection of software that works together to create a functioning product.

There are many operating systems that are not considered to be "Linux" (Windows is the most notable example). This is because they do not use the Linux Kernel. Other kernels include the Windows Kernel, Darwin (Apple's proprietary implementation that is run on Max), BSD (An alternative to linux), and several others. The kernel is the most integral part of an operating system - if an OS uses the "Linux" kernel, it's considered Linux. If someone pirated the Windows kernel and made a new OS with it, that OS would technically be "Windows".

[[https://www.geeksforgeeks.org/kernel-in-operating-system/][What is a kernel?]]
[[https://www.baeldung.com/cs/os-kernel][Kernels in Computer Science]]

** Distributions
A Linux distribution, often called a distro, is a complete operating system built around the Linux kernel. It includes the kernel itself, system libraries, utilities, and software applications. There are *many* different distributions, but some of the most notable ones include /Ubuntu/, /Debian/, /Arch Linux/, and /Fedora/.

*** What are the differences between distributions?
Differences between distributions primarily stem from:
- **Package Management:** Every distribution uses a specific package manager to install, update, and remove software. This is fundamentally just a piece of code written to search internet databases for code files, download them, install them to the correct place on your hard drive, and perform setup steps to ensure that the operating system recognizes the newly installed software. Different distributions will use different package managers as a default, but it is possible to use alternate package managers in many cases.
- **Default Software:** Distributions vary in the selection of pre-installed software. When I say "pre-installed software", I am referring to the programs that make the operating system function, not user level applications. This is the "GNU" of "GNU + Linux". This default software includes collections of drivers, compatibility layers, libraries, and many other pieces of low level code that act as a "black-box" for basic system functions.
- **Philosophy and Target Audience:** Some distributions focus on stability, while others prioritize cutting-edge software. The most popular operating systems are those that were created to solve a problem or address a complaint. For example, *Arch Linux* exists to present its users with the newest and most cutting edge code available. As soon as a developer releases code (whether it works or not) it is available to be installed using Arch Linux's package manager. *Debian* on the other hand, specifically exists to be stable and usable long term with minimal effort. The maintainers for Debians package manager take years to vet, test, and review packages before they are available for download. *Kali Linux* is another example. It is based on *Arch*, but it was not created out of any interest in package availability. Kali Linux was created specifically to present an environment with all the necessary tools and setup to PenTest networks (Hack into things).

Each distribution has its own community and support channels, influencing user experience and assistance available. Much of the advice that applies to one distribution will apply to others however. This is the beauty of Linux - Arch Linux and Debian (for example) are not alien universes to each other. They use different package managers, and have very different outlooks on the freedom that their users should be allowed, but at the end of the day much of the same code that makes Arch run is also present in Debian. 

[[https://www.geeksforgeeks.org/what-are-linux-distributions/][What is a Distro?]]
[[https://itsfoss.com/what-is-linux/][Why are there so many Distros?]]
[[https://en.wikipedia.org/wiki/Comparison_of_Linux_distributions][Linux Distro Comparison]]
[[https://www.redhat.com/en/topics/linux/whats-the-best-linux-distro-for-you][Red Hat - Choosing a Linux Distro]]

*** What is a desktop environment?
A *Desktop Environment* or *Window Manager* is essentially what turns your computer from "Terminal Only" to "Pictures and Pretty Things".

A window manager is a program that sets up a graphical interface, and allows seperate programs to run as "windows" inside of that interface. It applies rules to those windows, limiting their behavior and the degree to which the user can interact with them.

A desktop environment is a graphical interface designed to provide a consistent and user-friendly experience on Linux. Examples include GNOME, KDE Plasma, Xfce, and Cinnamon. It includes a window manager, icons, toolbars, and integrated applications (file manager, text editor, etc.).

A desktop environment provides the typical "Windows" experience - i.e., everything is provided. When you use a desktop environment, you install a large number of programs, but those programs are preconfigured to work together and present a cohesive interface. It is possible to install /only/ the window manager, for a more minimal experience (This is what I do). The window manager will provide /only/ the ability to "manage windows" (programs will open in a window, and the user is able to move them around, adjust how they look, and setup rules based on what that window is running), but the specific functionality and syntax varied based on the window manager itself.

[[https://itsfoss.com/what-is-desktop-environment/][What is a Desktop Environment?]]
[[https://wiki.archlinux.org/title/Desktop_environment][Arch Wiki - Desktop Environments]]
[[https://www.techopedia.com/definition/10043/window-manager][What is a Window Manager?]]
[[https://www.howtogeek.com/1119/what-is-dwmexe-and-why-is-it-running/][Window's Window Manager]]

** Lesson 1 - Key Terms
- [[*Kernels][Kernel]]
- [[*Distributions][Distribution]]
- [[*What are the differences between distributions?][Package Manager]]
- [[*What is a desktop environment?][Window Manager]]
- [[*What is a desktop environment?][Desktop Environment]]

