:PROPERTIES:
:ID:       931e43fe-6dcc-4d9c-9d16-0ea69410878f
:END:
#+title: MCTC
#+filetags: :Cadre:

[[id:c7116628-429e-4cd6-91da-00b938ef9d43][MCTC-Coach Meeting]]
* Day One
[[id:1a994b6f-6fae-4082-8ca1-dd97897a6770][MCTC-Training]]
** Drill
[[id:2eaac0e7-e947-451e-9526-ac457cd75864][Drill]]

6 to the front 3 to the rear
Proper commands - emphatic
Practice in front of a mirror
Heel and toe
Change Step - toe to heel, pause
FUCKING SNAPPY. WORK ON IT.
** SUMMER TRAINING LEADERSHIP FRAMEWORK

Excitement:
   Given an opportunity to influence an entire class of incoming cadets. I'm able to set the stage for their development and growth - both as people and as officers.
Nervous:
   The responsibility that comes with that opportunity and influence. I'm worried about messing up and either setting a poor example or failing to develop them in the correct ways.

Class Rules:
- Respect Others
- Judgement Free
- Understanding/Empathetic
- Open/Inclusive
- Positive Attitude
- Active participation

What does it mean to be a leader of character?
- Setting the example at all times
- Constant engagement
- Goal oriented/Purposeful
- Appropriate Energy
- Looking for help where needed
- Practice what we preach
- Balanced Relationship
- Upholding Core Values
- Safe and Helpful environment
- Authenticity
- HUMILITY!!! Authority doesn't mean shit.
  - A crown does not a king make; dunce in a golden cap.
- Open to Feedback
- Maintain Composure

The components to delivering a successful training:
- Have a clear goal
- Have well defined steps to reach that goal
- Different trainings require different objectives
- Keep the goal/purpose in mind
- Demonstrations are typically the most useful
- Making sure the entire group is on-board with the material being taught
- Repetition builds retention - along with other types of material reinforcement
  - Consult with the other cadre to accomodate everyone
- Making sure the trainees understand the goal behind the training
  - As much as is practical, sometimes you do have to say "Because I said so"
- Ensure consistant priorities among cadre
  - This is what the regs are for. Total adherance to the regulations
- Manage your reactions - you are always being watched


3 parts of an objective:
- Condition
  Tools, required items, specific situations/scenarios

- Performance
  Procedure or product, proper outcome

- Standard
  Within a given time, Accuracy, Procedural steps, etc


*CGPortal has program curriculum outlines*

*** Laws of Learning
*Readiness*
- Present an effective learning environment
- Make sure they know they can ask questions in the right situations
- Ensure proper engagement, cadre set the tone
  - If there's lack of engagement, it's probably coming from a lack of engagement/intensity from the cadre.


*Intensity*
- The more excitement material creates, the more likely to be remembered.
- Try to create hands on experiences or incite emotional responses from the trainees.

  
*Exercise*
- Practice makes perfect
- Ensure that repetition is a priority, you can't expect them to do something once and immediately understand it
  
  
*Primacy*
- Once you learn information, it's incredibly difficult to reteach it.
- As phase 2, we will have to adjust to what was taught during the first phase.
- Your first impression is what you take for the truth.

- Ensure proper communication between groups and among current group
- Get basis of understanding before beginning any instruction
- Make sure all information is communicated in a permanent fashion

- All cadre should have an understanding of every collateral.
- Make sure you maintain a proper continuum. If you start at 100, you have no where to go.

  
*Effect*
- Learning is strengthened when it's viewed positively. Create a positive environment around informational training
- Learning is weakened when its seen negatively. Try to avoid negative connotation around training (for example, don't phrase drill as a punishment)
- Learning happens *most* effectively when it results in satisfaction.

  
*Recency*
- We typically remember the most recent material covered.
- When teaching, we should build on previously covered material.
- All teaching should be incremental. 



*** Attention and Memory
Attention
- "Eyes"
- Verbally emphasize important pieces of information
- Vary your speech patterns - The same way you would with drill commands
- Engage the trainees - have them participate to some degree
  - This can involve having them repeat what you say, copy your movements, or popcorn the information
- Keep the trainees active (even if this isn't something you can participate in)
  - Have them move around during an evolution, basically keep them from falling asleep
- Cold-call when quizzing
- State the expectation - "If you don't know X, Y will happen"


Memory
- Make sure they can repeat or execute information/commands after it's been presented
- "Test" them on whatever we've just covered
- E.G. For drill commands, once I've taught it, have the group execute it. If there seems to be confusion, break it down either within the group or break down the information (seperate people, or teach the information piece by piece). 

** UNDERSTANDING THE ROLE OF CADRE
What is the purpose of the Cadre program?
- To develop and teach incoming cadets
- Develop leadership among second class cadets
- Practice teamwork
  
Why do we have Cadre?
- To train new swabs
- Instill the Coast Guard core values in the incoming class


Take this seriously - maintain a reputation, and back the reputation up with action.
Stay squared away now, during the summer, and during the rest of the school year. 

** COAST GUARD LEADERSHIP MODELS: Train the Trainer (Session 1)
*Interact Model*

Used to address performance or behavior
Behavior needs to meet one of 4 "questions" in order for the Interact model to apply
- Is the bahavior having a negative impact on the job
- Is the behavior preventing others from doing their job
- Is the behavior preventing you from doing your job
- Is the behavior a violation of unit or CG policy

1. Communicate the situation
   - State the standard/expectation, state the difference between what is currently happening in a *specific* and *non-punishing* way.

2. Pause, allow time for a response. If there is no response, ask /why/. Allow ample time (7 seconds or so).

3. Diagnose
   - Find out why this happened.


Categories of performance problems
1. Role Clarity
   "If i'd known, i'd have done it"
   - Response: Re-establish role/expectation, Establish a follow up, Then follow up
2. Ability
   "If I could have done it, I would have"
   - Response: Show/Tell how to accomplish the expectation or provide them the materials they need, Re-establish role/expectation, Establish a follow up, Then follow up 
3. Willingness
   "I know what is expected but I chose not to do it"
   - Response: Communicate Natural Consequences (To the job, To others, To the Supervisor, To them), Stop at compliance, Re-establish role/expectation, Establish follow up, then follow up.
4. Emergent Problem
   Extreme situations (Sexual harrasment, Familt Loss, Financial, etc.)
   - Response: Find out what it is (listen), Solve or postpone (How urgent is it), Return to original issue if appropriate


Ronnie/Jamie: Cadre
Berger: Ability
Me: Role-Clarity
Carson: Willingness
Jimmy: Emergent Problem


* Day Two
** Shout Out Activity

** GROWTH MINDSET AND HEAT MOMENTS
What is a growth mindset
- Means being open to change and development
- Approaching something willing to learn, and most of all willing to be wrong
- Think about your position on the topic, and approach whatever it is with vigor and intention, but be able to recognize when that isn't correct.

Possible Roadblocks
- Stubborness
- Desire to be right
- "Black and White" Mindset
- Seeing a situation as something where only one option may work
- Biases or Previous Life Experiences
- Comfort
- Fear of Failure


I am concerned about not knowing information well enough, or presenting incorrect information. I can adopt a positive growth mindset, and instead view this worry as an opportunity to practice my own understanding of the information, and ensure that I review all information with my cadre before I present it to the trainees.

*Heat Moment* - "For an individual or team, heat is a stressful assignment that pushes you to your limits in a way that can be career-defining. It can be mentally taxing, emotionally confusing, or physically demanding - and sometimes all at once"

Examples of possible "Heat Moments":
- Disagreements
- High intensity evolutions where we have to motivate the swabs
- speaing w/o thinking
- Swab in danger/medical emergency

How do we get through the heat moment and develop as a leader from it:
- Seperate yourself from the situation
- Breathe and get some perspective
- Keep a level head & understand what you need to do in the situation

This is crucial to developing as a leader. It helps to learn control over impulses and emotions.




** PRINCIPLES OF EFFECTIVE FEEDBACK
What is Feedback?
- Respectful and purposeful information about performance and how best to improve

Can you distinguish between feedback and correction?
- Feedback involves presenting ways to improve and progress from the current position. Correction is simply identifying and pointing out deficiencies.

Swab Summer focuses a great deal on negative feedback and reinforcement. This is intended to eliminate deficiency and cement the idea that the swabs should seek perfection. While this does mean that we aren't focusing a great deal on positive reinforcement we are able to use a lack of negative reinforcement just as effectively.

** DiSC PROFILE APPLICATION
C - Conscientiousness
- Analytical
- Reserved
- Precise
- Private
- Systematic


What characteristics of this style help me to be a great leader?
- I am able to analyze and process situations well.
- 

What characteristics get in the way of being a great leader?
- Take too long analyzing situations
- Would prefer to look at situations from a theoretical perspective rather than a practical one

How can I be a more effective leader?
- Make an effort to be more assertive
- Force myself to take charge of situations and evolutions

How do I approach conflict?
- I tend to deal with conflict by analyzing the causes and best solutions to the issue
- This is useful to me, but others may not see it as helpful and can see it as supercillious or condescending

How do I react to stress?
- Revert to the logical solution, which may not always be the correct one.
- Tend to go and do my own thing when I see that things are not proceeding well

How am I misunderstood?
- People might think I don't care
- Seen as condescending
- 

** TAKING CARE OF PEOPLE
What does it mean to take care of people?
- Ensuring that each individual ahs everything they need to succeed on a personal and a professional level.

Maslow's hierarchy of needs outlines 5 basic categories of needs that each person has:
Self-actualization, Self-esteem, Love and Belonging, Safety and Security, and physiological needs
We challenge each of these categories in unique ways, depriving them of food, sleep, physical contact, emotional connection, and validation.
We also provide for these needs in ways  that are unique to the cadre-swab relationship, ensuring their safety at all times, providing a very tough love support system.
It's crucial to understand the needs of the people you lead and understand how your leadership both provides for and challenges those needs.


How can I incorporate these needs to ensure that I am taking care of myself?
- Have a checklist that i use to ensure that I'm getting the proper amount of sleep, food, water, etc.
- Ensure that I'm taking a portion of each day for reflection and seperation from people and the day.


How can I ensure that I use these needs to take care of the rest of my cadre section?
- Check in regularly
- If i notice something is off, then mention something to that person.


Make sure cadre roles and responsibilities switch on a regular basis. 
Implementing a duty schedule will help set accountability - making sure cadre take care of themselves. 


* Day Three

** Conflict Management
Words that come to mind when I think of conflict
- Disagreement
- Engaging
- Grating
- Strong Opinions
- Rigid
Feeling related to conflict:
- Irritation
- Stubborness
- Anger
- Competition
After conflict I feel:
- Angry
- Irritated
- Combative
- Confrontational

Conflict styles:
Competing (I win you lose), Collaborating (I win you win), Compromising (1/2 win 1/2 win), Avoiding (I lose you lose), Accomodating (I lose you win)

Each of these are useful in their own circumstance
Competing: Exigent issues
Collaborating: Larger groups where we have people to mediate, good default
Compromising: one on one, not time sensitive
Avoiding: immediate task
Accomodate: When dealing with superior or unknowns.

Conflict can be approached with the RESOLVE model
Reach out, Engage in conversation, Seek to solve the problem, Open up, Listen intently, Voice solutions, End on a good note
** OCS
We had a very productive talk with two OCS cadre. Unfortunately I don't remember much of what they had to say, but I do remember them mentioning to take time to form as a team and to focus on not stretching ourselves beyond our limits. There's a time and a place for different interactions. If the swab needs support, give it to them. If they need a question answered, or want to understand the motivation behind something, explain it. Most of all, we should be the examples - on a physical and a mental level. We should understand almost everything we're teaching them. 


* Day Four
** COAST GUARD LEADERSHIP MODELS: Tuckmans Model Applications
Forming:
- Teams have just come together. They don't know much about each other yet, and they haven't figured out how to function as a team yet. Everyone very polite and considerate of each other's place - which is good, but unproductive
Storming:
- Teams have started to grate on each other. Individuals are starting to come into conflict, and as membvers learn more about each other, they gain confidence in themselves. There's going to be less politeness as people start to get more comfortable voicing their opinions over others. Groups need to enter this stage in order to improve and gain efficiency as a team
Norming:
- Team accepts their goals and roles, should now fully understand themselves, their peers, and the group. They work positively together to accomplish goals, are comfortable with each other.
Performing:
- Best place to be. They focus on achieving goals, and should have moved past disagreements and petty opinions to solve conflicts positively. 
Adjourning:
- The group is disbanding, some dissapointment over the gradual feeling of failure and seperation.
** COAST GUARD LEADERSHIP MODELS: Leadership Action Model Applications
Made up of a graph divided into quadrants. two perpendicular scales, Ability and Motivation.
High ability and low motivation requires an instructur to /Inspire/ the trainee (top left)
Low ability and motivation requires an instructor to /Teach/ and /Inspire/ the trainee (bottom left)
High ability and moticvation requires an instructor to /Trust/ the trainee (top right)
Low ability and high motivation requires an instructor to /Teach/ the trainee (bottom right)

Teach
- Task focused
- high training
- reviuew work
- clear task direction
- knwledge and skill


Inspire
- Member focused
- task meaningfulness
- listen
- remove barriers
- show progress
- feedback


Trust
- Autonomy
- check work occassionally
- Independance
- Involve in decision making


** CULTURAL FLUENCY
What does it mean to be culturally fluent?
- be respectful
- seek knowledge and understanding about another persons culture
- get a basinc understanding before asking

** COAST GUARD LEADERSHIP MODELS: Interact Model Application

** EMOTIONAL INTELLIGENCE AWARENESS


* Day Five
** COAST GUARD LEADERSHIP MODELS: TLC Applications

** EMPATHETIC LEADERSHIP

Empathy
- putting yourself in someone elses shoes
- Treating them as people, not robots (when necessary)
- People perform the best when they think you care about them


** Reflection
What am I looking for out of swab summer?
- A chance to get out of my comfort zone
- I've had leadership positions before, but this will be my first time being responsible for actual people (as opposed to just money or tasks/results)


What will cause tension for me?
- Differences of opinions
- Perceived lack of effort
- Lack of preparation
