:PROPERTIES:
:ID:       2eaac0e7-e947-451e-9526-ac457cd75864
:END:
#+title: Drill

[[id:931e43fe-6dcc-4d9c-9d16-0ea69410878f][MCTC Drill practice]]


* Personal Priorities

** Appearance
Appearance is everything.
Sets an impression, creates the image that you present.
Uniform must be perfect.

** Presence
Force of presence determines the response of the platoon.
Commands delivered with force and impact are more effective, and more likely to be followed well.

** Knowledge
Must have intimate knowledge of the material.
If I don't know drill, I can't expect anyone else to know it either.
I must know it well, and be able to thouroughly answer any question that is posed of me.

* General Overview

** Stress the basics

First phase should focus on cementing the basics until its second nature. Brace should already come easily, so the primary focus should be solidifying proper drill practices, then teaching the execution of technique. Once good practice is built, movements will follow naturally. Focusing on the small things will make teaching the larger things significantly easier. 

*** Important points to stress
- Brace
  The foundation of good drill. Without good brace, you /can't/ drill well. This should be easy to practice; swabs should be able to recite the POA upon request, for the first week, drill them on this. After that, harp on the small things (hands curled, along the trouser seam). If they aren't doing it during the day, they probably aren't doing it during drill either. 
- Deliberate Motion
  One of the largest speedbumps when teaching drill to newcomers is hesitancy. Most green platoons will bunch on "Forward March" and lag on turns, etcetera. This is remedied through consistent practice at a basic level. Start at Mac, Forward March, Halt after 5-10 paces, repeat until the formation is used to moving as a unit.
  *Sidenote* - may be useful to teach to-the-rear so that this evolution becomes more seamless
- Proper knowledge
  Teach proper spacing and how to maintain it. Focus on drilling it into them. When doing the stop and start drill, have them check spacing every stop (needs to be quick, so teach "Dress Right Dress" well, and focus on snappy movement) 



This is a test  -  will onedrive update?? the world may never know
