:PROPERTIES:
:ID:       aecae854-00c5-4708-a18a-97d4386a4070
:END:
#+title: Signal
#+filetags: :DSP:

 Any physical quantity that varies with time space or any other independent variable or variables.

 Mathematically, we define a signal as a function of one or more independent variables
 $s_{1}(t)=5t$
 $s_{2}(t)=20t^2$
$s(x,y)=3x+2xy+10y^2$

In these cases, the signals are precisely defined by specifying the relationship between the result and the independent variable.
This is not always the case. There are some signals that can not be accurately represented by such functions.
For example, a sound wave could be /approximated/ by a function such as:
$\sum_{i=1}^{N}{A_{i}(t)sin[2\pi F_{i}(t)t+\theta_{i}(t)]$
where $A_{i}(t)$, $F_{i}(t)$, and $\theta_{i}(t)$ are sets of (potentially time varying) amplitudes, frequencies, and phases of multiple sinusoids.

Whenever we look at signals, we must also examine how they are generated.
Signal generation is typicaly associated with a [[id:53c1025a-8da7-48c9-9a4c-c7f199b68c4e][System]] that responds to a stimulus - also known as a [[id:d8a25c0c-319d-4271-8422-0b95e1610179][Signal Source]]. 
 
* Signal Classifications
** Multichannel and Multidimensional Signals
Signals are described by functions of one or more variables.
These functions can have a variety of different output types; real, complex, etc

Sometimes, signals are generated by multiple sources. These can be represented in vector form.
$\begin{bmatrix}s_{1}(t)\\ s_{2}(t)\\ s_{3}(t)\end{bmatrix}$
We refer to such vectors as /multichannel signals/. Each component depends on a certain number of independent variables. This number of variables is known as the signals /dimension/. The following example consists of a 3 channel, 3 dimensional signal.
$\begin{bmatrix}I_{r}(x,y,t)\\ I_{g}(x,y,t)\\ I_{b}(x,y,t)\end{bmatrix}$
** Continuous Time vs Discrete Time Signals
Signals can either be continuous (otherwise known as analog) or [[id:4c08afb3-7075-4b7d-8887-8086c534a61c][Discrete]].
Continuous signals are defined for every value of time, and take on values in the continuous interval.
Discrete time signals are defined only at specific moments in time. These time instants do not need to be spaced evenly, but in practice usually are. 
** Continuous-Valued vs Discrete-Values signals
The values of continuous-time or discrete-time signals can either be continuous or discrete. If a signal takes on all possible values on a finite or infinite range, it is a continuous-values signal.
If the signal takes on values from a finite set of possibilities, it is said to be a discrete-values signal.
Usually these values are equidistant.

When a discrete-time signal has a set of discrete values, it is known as a digital signal. 
** Deterministic vs Random signals
In order to analyze and process signals mathematically, we must first be able to represent them mathematically. This representation is known as a /signal model/.

Any signal that can be uniquely described by an explicit mathematical expression, data table, or well-defined rule is called /deterministic/. This is used to indicate the fact that all *present*, *past*, and *future* values for this signal are known precisely, without any uncertainty. 
