:PROPERTIES:
:ID:       978dd04c-79e3-4153-9efc-54a03c0935ab
:END:
#+title: Microsoft Internship

* Meeting Notes
** Check-In with Robert Soligan and Navy Team - 25JUN2024

*Intro*
- Jadyn Dessalines - 2022 Naval Academy Grad. LTJG. Cyber Grad, worked with Navy Cyber. 
- Christopher Neef - Chief. Worked in IT with the Navy since 2005. Just started moving into Cloud arena. 19 Years. Yale postgrad, thesis BDP and federating data over BDP. Previously certified as a Google Architect.

*Meeting with Chief and Ma'am*
Add their calendars in outlook, find a time that works for everyone for one-on-one mentorship meeting.

*Training Material that works for them*
Know the products and what they do.
Work through provided training.
ESI? (aka.ms/msi) - not sure what this is or how it is useful

*Their Conversation*
Trying to get Copilot/OpenAI for the Navy

Azure Open AI (AOAI) - ChatGPT isolated to a tenant. Information stays local to the client and does not go back to OpenAI.
There is an API for your AOAI Instance, allows you to create automations and feed information to the model.
This specifically allows for some integration with Azure capabilities. Soligan showed an example where he had configured the Azure portal so that, for an actual organization, whenever there was an incident report (not sure what for) it made an API call so that the AOAI model could summarize the incident report. The model was able to assign a severity, a general description, and a "next action" (I think? I only managed to read about half.). The model also created tasks based on each report to indicate next steps that should be taken.
** Navy Shadowing: Copilot for Security PG Conversation - 26JUN2024
*In the Meeting*
- Jadyn Dessalines
- Robert Soligan
- Kevin Friedemann
- Daniel Huynh
- Christopher Neef

*Copilot for Security*
Chat GPT, specifically for security issues. Has access to /your/ microsoft data.
Works in a standalone and an embedded format.

Standalone provides in-depth functionality and can perform some incredibly complex tasks.
Embedded is much simpler to work with, and integrates with your daily workflow as part of the UX.

Daniel Huynh mentioned a range of "Copilot Variations", it would be interesting to see how exactly those variations are implemented. They could be completely separate models, trained from scratch to fill different roles, or they could be the same model that is fine tuned based on a different set of information (This is the most likely method.) Alternatively, they could all be the same model which is being altered based on prompts and specific information fed into the model at runtime. If, as I suspect, the model is the same but fine tuned for a specific task, I wonder how that will affect the development cycle. Will there be a lag for the more specific copilot variations, as the central model is developed?
** NCDOC and Blossom Baker
*In the Meeting*
- Robert Soligan - Not Present
- Christopher Neef
- Jadyn Dessalines
- Joseph Church
- Kevin Friedemann
- Blossom Baker

*NCDOC*
-  The Navy shadowing folks

*Blossom Baker*
One of the primcipal cloud security architects at Microsoft
Computer Science Bachelors, Masters in Software Engineering and MBA at Georgetown and Cyber Security and Policy at Harvard
Started as a Software Engineer at Lockheed, went to management
Went to Government Position
Now at Microsoft

*Opportunities and Lessons Learned*
Early stage in career - advice for younger self
- Stay focused
- Learn as much as possible
- Pay attention to where industry is headed
- Baby steps - every day to learn
- Where you are now may not seem like you have "succeeded", but its a continuous path.
- Shape your career and your character - professional discipline
- Dont be afraid to fail or take risks in learning
- Failure is how you learn


*Career Journey*
Came into MS as an industry professional
- Crawl Walk Run
Solid foundation gives you something that nothing else can
Understanding the foundation of any job, task, solution, etc is the most important part of succeeding.
Your knowledge base should be broad to maintain a strong foundation

*Cyber Security Architect vs Other types of Architect*
Was in management before came to MS.
- Cyber Security Architect - person who is responsible for understandinf the entire infratructure/architecture for an environment (The foundational setup) (Brilliant at the basics).
  Person who can have a conversation with a customer about the exsting environment, where they might have gaps, and where they might improve efficienct/securiety.
  Examining connections and relationships between people and products.
  Ensuring that you can advise customers on security and providing information on threats that may be in the environment
  Design an optimal environment state.

  *Most common security challenge in the cloud*
  From what Baker's seen of the navy
  The enablement of security solutions
  Mission owners have not fuly enabled/configured the features in the solutions that they have purchased
  Third party products and integration is dificult.
  Ensure that you are fully utilizing what you purchase.
  Identity is a new boundary, where bad actors are directly impeorsonating credentialled users

  *Lessons learned/advice on managing identity in a multi-cloud environment*
  Limit the number of priviledged users
  seperate high performing assets
  All resources should be layered within the proper security controls.

  *Advice on identifying areas to expand your knowledge/foundation*
  For people like me and Joe who are still working toward an undergraduate degree and establishing that foundation, how can we identify areas to focus on or expand our understanding?

  Follow you r passion and your interests
  If you already know this is what you wanty to do, awesome

  Some people don't have that next sep (thats ok)
  Continue on the path where you are - each path/step will inform you .

  Its up to you to decide your path
  Pay atteentio to the market and what is going to sustain you

  If you have a passion in another area, you cant really go wrong

  Shes struggled in the past and working to iprove. Shes an ambivert. Buil your network
  Make sure someone knows your name.
  You do that with your performance, but also yourcharacter.
  Listen, arrive early, go the extra mile
  Focus on your network as well as your performance

  Half the batte is showingf up

  Never turn down an opportunity to learn

  Repetition is the mother of skill. Take certs, dont be adaid to fail ad learn from it.

  Read [[id:9c358a35-236c-490d-bffb-7dd57eb4d992][Atomic Habits]]
  
** Ian Leatherman: Conversation with NCDOC
*In the Meeting*
- Robert Soligan (not present)
- Jadyn Dessalines
- Christopher Neef
- Joe Church
- Ian Leatherman
- Kevin Friedemann
- Elisha Angeles


*Ian Leatherman*
MS for 2 years
11 years active with Navy, Submarines
Left submarines for WarCom (Next to NCDOC)
Came to Fleet Cyber, CIO Shop
Job at microsoft is to take Flankspeed (?) and expand that functionality to the entire government.
Currently a Maritime Cyber Warfare Officer with the reserves - MCWO?

I don't really understand any of what he's talking about. He is discussing the difference/relationship between usability and security.
Usability and security do not have to be mutually exclusive, but often are because of bad system design.

Talked about making sure that all different commands/units etc within the military use similar auth methods. This is because different sections use different auths, and different logs, and different methods to accomplish the same thiong. we can improve security and cost by consolidating to one common method.

*Key Terms*
Entra ID
F5
- Both are Auth methods?


*Moral*
'Zero Trust' can result in a better user experience

** One-on-One Meeting with Dessalines and Neef
*In Meeting*
- Jadyn Dessalines
- Christopher Neef
- Joe Church

*What do they do?*
NCDOC - Navy Cyber Defence Operations Command
DCO (Defence Cyber Operations)
Manage networks
Paired with navy network warfare command
Monitor network usage and acivity

Chief
- N65 Chief - had own division
- Scan/Patch/Scan
- Mainly leadership
- Keeping an eye on the watchfloor


Watchfloor is a 24/7 SOC (Security Operation Center)
Basically the Navy "Battle Bridge"

Dessalines
- After Graduation ,led development team
- Dev team is civilian, she is the only military leadership
- Started as a developer, actual technical work
- Microsoft provides support and advice on the telemetry that they have acecss to, but MS doesn't have access to classified info


Goal is to move the entire navy to the cloud and fuly implement 'Zero Trust'
IL - Impact Level
- IL1 -  IL4 Commercially available cloud
- IL5 CUI (Navy Standard for unclass)
- IL6 Secret
- IL7 TS

Check in regularly with those under you
- Know them, their family
- Be involved with everyone under you
- Dessalines does weekly meetinfs with every sailor under her to check in on what they are doing for their professiopnal development


** Meeting with John Rodriguez (Principal Architect)
*In Meeting*
- Robert Soligan
- Jadyn Dessalines
- Christopher Neef
- Elisha Angeles
- John Rodriguez
- Joe Church
- Kevin Friedemann


*John Rodriguez*
Lead architect for the security practice in the federal consulting
"what should we be doing 6 months from now"
"how do we get ready to do those new things"
"How do we partner with other organzations to achive those things"
"How do we partner with other parts of microsoft"
"How do we prevent problems for higher ups"
focuses on DOD.

*Lessons learned from other branches*
2 big programs - flakspeed (navy) and itaz? (Army)
- both targeting zero trust
- both pretty far advanced

Biggest questions surround telemetry - what data to collect and how to use it.
must ensure that the data you ingest is actually valuable and gets used.
Biggest lesson learned is to ensure that you actually use the data you take in.
2 of the hardest parts are data protection and software factory (mechanism for converting legacy applications so that they are more modern. Less monolithic, serverless, function based)

*Question for Jadyn/Chris* - If you had control, what would you change
- Move away from "legacy archiotecture" that they still try to embed in everything
- Improve the way you presenbt the 'problem'
- Give an identity ONCE - i.e. shift to a single identity provider across the board.


*Zero Trust*
You no longer have to worry about outside networks.
It involves a continuous re-evaluation to determine whether someone should have access to resources.
Zero Trust involves starting from a point of "Zero" trust, then each individual person works up to a point of trust.
Shouldn't automatically trust an IP based on their source network (VPN's are a thing).
You should evaluate each individual to determine, regardless of IP, whether they should be trusted.

*Where do you see AI going*
"Great Equalizer"
Can help a junior analyst provide results that you would expect from a senior analyst.
Can simulate results of years of experience.
Makes hiring process easier by reducing the expertise needed.

Highlights "sins of the past".
AI will have access to the data of the company that created it, so if a company has poor data security, the AI will find data that it should not have access to.
This will help identify and incentive-ize better practice. 


** SME Corner Series - Azure Attack Paths (Part 1)
*In the Meeting*
- Jadyn Dessalines
- Christopher Neef
- Shankar Subramaniyan - Speaker
- about 150+ more people


** John Barbare - Meet and Greet
*In the Meeting*
- Christopher Neef
- Elisha Angeles
- Jadyn Dessalines
- John Barbare
- Joe Church
- Kevin Friedemann

*John Barbare*
Army
5.5 years Defense contracter
5.5 years, customer success unit



* My Work
[[id:b1a8d451-fc98-409f-9287-9d56d8696495][Microsoft Azure]]
- Following the Microsoft Learn "AZ900" course, to gain a base level understanding of Microsoft azure.

* Notable Links
aka.ms/discounts
aka.ms/ESI







