:PROPERTIES:
:ID:       5624e542-d3da-4e85-9177-b6304bdfd157
:END:
#+title: Proofs
#+filetags: :Discrete:

* Direct Proofs
- Take the hypothesis and travel a sequence of implications leading to the final conclusion
Essentially, we are "directly" proving a hypothesis using implications and nothing more.
Obviously we can prove those implications any way we choose, but the general proof will look like:
$A\implies B\implies C\implies D,\ \therefore\ A\implies D, \text{ given } A\therefore D$ 


* Proof by Cases
We can sometimes make a direct argument simpler by breaking it into a series of "cases".
One of these cases must hold true, and each should lead to the desired conclusion


* Proof by Example
Only useful when proving the /existance/ of something, or /displroving/ something.
In these cases, we only need one case to prove that something exists or is not true.

Ex.
if $xy$ is a rational number, then x and y are both rational.

a. State converse
- If x and y are both rational, then the product $xy$ is rational.
b. Which is true, the original or its converse?
- Converse
  Why?
  X and Y both rational numbers, $x=\frac{p_{1}}{q_{1}};\ q_{1}\ne0;\ p_{1},q_{1}\in\mathbb{Z}$ Same for y.
  $\therefore xy=\frac{p_{1}p_{2}}{q_{1}q_{2}}$ and $p_{1}p_{2}\in\mathbb{Z}$, so xy is rational.


We will now use a proof by example to prove that this is false.
In order to do so, we will produce a counter example.
0 is rational. $\pi$ is irrational.
$0*\pi=0$. A rational number multiplied by an irrational number created a rational number.
Therefore, it is false that if a product is rational then the factors in that product are both rational.


Ex.
If x and y are rational, is $\frac{x}{y}$ rational?

This is false for any case where y=0. 

* Proof by Contra-positive
$A\implies B$ is only true if $\lnot B\implies \lnot A$ is true as well.
This is the idea that we use to prove a hypothesis with the contra-positive.


* Proof by Contradiction
Assume ~p and find a contradiction

Ex.
Prove that there is no largest integer.
- There does not exist an X in Z such that X is greater than or equal to Y for all Y in Z.
