:PROPERTIES:
:ID:       e9421f7c-bc43-4dfd-b5ac-65328e814112
:END:
#+title: Mathematical Statements
#+filetags: :Discrete:

A sentence which is either *TRUE* or *FALSE*

- It is raining
- A Project can run
- \pi=3.14

* Types of Mathematical Statements
- Atomic (A single statement)
- Compound (Combined statements)


* Operations on Mathematical Statements

To connect multiple statements - connectives
- OR
- AND


How does either of these /connectives/ influence the "truth value" of a compound statement?

Example:
Let /P/ be the statement "My jacket is blue"
Let /Q/ be the statement "Our classroom is pink".
- P is true, Q is false.

*Case 1*: =P OR Q=
What is the truth value of the compound sentence in case 1?
- My jacket is blue, or our classroom is pink.
  One is true, the other is false, therefore the truth value is =true=.
*Case 2*: =P AND Q=
This is false.


Example:
Let /P/ be the statement "My jacket is blue"
Let /Q/ be the statement "The floor is blue"
=P OR Q= - true (Since both are true)
=P AND Q= - true (Since both are true)

*Truth Tables*
| P | Q | P or Q | P and Q |
| T | T | T      | T       |
| T | F | T      | F       |
| F | T | T      | F       |
| F | F | F      | F       |

=AND= represents a conjunction, and can be represented by: \land
=OR= represents a disjunction, and can be represented by: \lor

  

Also [[id:76420d08-3412-42d6-b7fd-1d3d1e301d77][Negation]], [[id:97d301ee-5c6e-4fd4-b18f-ab38b72ad918][Implication]],[[id:79dc34a1-9050-4695-909b-559e59debbbc][ Double Implication]]
