:PROPERTIES:
:ID:       978dd04c-79e3-4153-9efc-54a03c0935ab
:END:
#+title: Microsoft Internship

* Meeting Notes
** Check-In with Robert Soligan and Navy Team - 25JUN2024

*Intro*
- Jadyn Dessalines - 2022 Naval Academy Grad. Cyber Grad, worked with Navy Cyber. 
- Christopher Neef - Chief. Worked in IT with the Navy since 2005. Just started moving into Cloud arena. 19 Years. Yale postgrad, thesis BDP and federating data over BDP. Previously certified as a Google Architect.

*Meeting with Chief and Ma'am*
Add their calendars in outlook, find a time that works for everyone for one-on-one mentorship meeting.

*Training Material that works for them*
Know the products and what they do.
Work through provided training.
ESI? (aka.ms/msi) - not sure what this is or how it is useful

*Their Conversation*
Trying to get Copilot/OpenAI for the Navy

Azure Open AI (AOAI) - ChatGPT isolated to a tenant. Information stays local to the client and does not go back to OpenAI.
There is an API for your AOAI Instance, allows you to create automations and feed information to the model.
This specifically allows for some integration with Azure capabilities. Soligan showed an example where he had configured the Azure portal so that, for an actual organization, whenever there was an incident report (not sure what for) it made an API call so that the AOAI model could summarize the incident report. The model was able to assign a severity, a general description, and a "next action" (I think? I only managed to read about half.). The model also created tasks based on each report to indicate next steps that should be taken.
* * Navy Shadowing: Copilot for Security PG Conversation - 26JUN2024
*In the Meeting*
- Jadyn Dessalines
- Robert Soligan
- Kevin Friedemann
- Daniel Huynh
- Christopher Neef

*Copilot for Security*
Chat GPT, specifically for security issues. Has access to /your/ microsoft data.
Works in a standalone and an embedded format.

Standalone provides in-depth functionality and can perform some incredibly complex tasks.
Embedded is much simpler to work with, and integrates with your daily workflow as part of the UX.

Daniel Huynh mentioned a range of "Copilot Variations", it would be interesting to see how exactly those variations are implemented. They could be completely separate models, trained from scratch to fill different roles, or they could be the same model that is fine tuned based on a different set of information (This is the most likely method.) Alternatively, they could all be the same model which is being altered based on prompts and specific information fed into the model at runtime. If, as I suspect, the model is the same but fine tuned for a specific task, I wonder how that will affect the development cycle. Will there be a lag for the more specific copilot variations, as the central model is developed?
** NCDOC and Blossom Baker
*In the Meeting*
- Robert Soligan - Not Present
- Christopher Neef
- Jadyn Dessalines
- Joseph Church
- Kevin Friedemann
- Blossom Baker

*NCDOC*
-  The Navy shadowing folks

*Blossom Baker*
One of the primcipal cloud security architects at Microsoft
Computer Science Bachelors, Masters in Software Engineering and MBA at Georgetown and Cyber Security and Policy at Harvard
Started as a Software Engineer at Lockheed, went to management
Went to Government Position
Now at Microsoft

*Opportunities and Lessons Learned*
Early stage in career - advice for younger self
- Stay focused
- Learn as much as possible
- Pay attention to where industry is headed
- Baby steps - every day to learn
- Where you are now may not seem like you have "succeeded", but its a continuous path.
- Shape your career and your character - professional discipline
- Dont be afraid to fail or take risks in learning
- Failure is how you learn


*Career Journey*
Came into MS as an industry professional
- Crawl Walk Run
Solid foundation gives you something that nothing else can
Understanding the foundation of any job, task, solution, etc is the most important part of succeeding.
Your knowledge base should be broad to maintain a strong foundation

*Cyber Security Architect vs Other types of Architect*
Was in management before came to MS.
- Cyber Security Architect - person who is responsible for understandinf the entire infratructure/architecture for an environment (The foundational setup) (Brilliant at the basics).
  Person who can have a conversation with a customer about the exsting environment, where they might have gaps, and where they might improve efficienct/securiety.
  Examining connections and relationships between people and products.
  Ensuring that you can advise customers on security and providing information on threats that may be in the environment
  Design an optimal environment state.

  *Most common security challenge in the cloud*
  From what Baker's seen of the navy
  The enablement of security solutions
  Mission owners have not fuly enabled/configured the features in the solutions that they have purchased
  Third party products and integration is dificult.
  Ensure that you are fully utilizing what you purchase.
  Identity is a new boundary, where bad actors are directly impeorsonating credentialled users

  *Lessons learned/advice on managing identity in a multi-cloud environment*
  Limit the number of priviledged users
  seperate high performing assets
  All resources should be layered within the proper security controls.

  *Advice on identifying areas to expand your knowledge/foundation*
  For people like me and Joe who are still working toward an undergraduate degree and establishing that foundation, how can we identify areas to focus on or expand our understanding?

  Follow you r passion and your interests
  If you already know this is what you wanty to do, awesome

  Some people don't have that next sep (thats ok)
  Continue on the path where you are - each path/step will inform you .

  Its up to you to decide your path
  Pay atteentio to the market and what is going to sustain you

  If you have a passion in another area, you cant really go wrong

  Shes struggled in the past and working to iprove. Shes an ambivert. Buil your network
  Make sure someone knows your name.
  You do that with your performance, but also yourcharacter.
  Listen, arrive early, go the extra mile
  Focus on your network as well as your performance

  Half the batte is showingf up

  Never turn down an opportunity to learn

  Repetition is the mother of skill. Take certs, dont be adaid to fail ad learn from it.

  Read [[id:9c358a35-236c-490d-bffb-7dd57eb4d992][Atomic Habits]]
  

* Notable Links
aka.ms/discounts
aka.ms/ESI






