:PROPERTIES:
:ID:       d6881214-4358-4719-a1c3-df2b44b990cb
:END:
PROPERTIES:
#+filetags: :Boat:Cadre:
:ID:       cf92e170-3530-4dd2-a15c-187aef0c3e41
:END:
#+title: 2023-06-27

* Daily Log
Yesterday was the first day of Swab Summer. It's honestly a little surreal seeing all the swabs onboard, knowing that in 3 weeks I'll be responsible for them. I don't feel ready at all, and i know I'm going to screw something up.
We're working on the T-boats this week (Training Boats). We learn to steer and maneuver, and it seems like there's a particular focus on approaches and maneuvering at the dock. That's something else I don't feel ready for - I have no idea how to handle all this newfound responsibility other than tackling it head-on.

Woke up at 0530 to reveille, the POD said breakfast started at 0615, so I took an early shower to start off the day, then went down to breakfast. Of course they didn't have food out yet; apparently they thought it started at 0630. So I went back to my room and got my own breakfast of cereal. Not the best start to my first day of T-Boats.

Today was productive overall. We learned how to start up the boat, we got to practice springing some, I was the Conn right before lunch. The day seemed sort of boring after lunch; I pretty much sat on deck sleeping while the rest of our boat finished their turns as Conn. I had a good time, and it feels as though t-boats are going to be fun. 

** What went well?

** What didn't?
"Confrontation" with the wardroom staff

** What can I change?
Focus on keeping my mouth shut and not making a problem where there doesn't need to be one. 
