:PROPERTIES:
:ID:       fad36dae-0b5e-45ed-8b5d-206bc7536216
:END:
#+title: 2023-06-12
* 06:40 AM: Halfway through my two weeks of leave
This is the end of my first week of leave. Terry picked me up from OPS week last friday, I stayed with him through Saturday and went to a concert with my grandfather on sunday. We saw some modern composer who I wasn't terribly impressed with, but we also saw Carmina Burana, which was awesome. I spent the next few days at home with my mom, took her to the airport on Wednesday, went to see LT, then went to my dad's. It was good to go back to PH. I saw Becca there, I wanted to go see Petey but she seemed busy. LT was pretty helpful; general tips on leading. Spending time with my dad was also good. He got me some Vols merch - which I think I'll actually wear. Terry picked me up on Saturday and we've spent the last two days in Deltaville. We went fishing Sunday and now we're getting ready to drive back. It's been a good week so far - I do wish I had more time to just relax, without so much going on, but I've had a good time. I'm looking forward to going to Danny's graduation, and then getting back to the Academy; even though it'll be tough; will honestly be nice. The place is starting to feel a little better - I guess just because I'm getting more comfortable. 
