:PROPERTIES:
:ID:       71c5146f-4913-40b8-b47a-bdb1e9d75594
:END:
#+title: 2024-02-24


* Daily Log
Today was long. Saturday; supposed to be a day for relaxation. Reflection. Decompressing from a week of work and stress.
Today felt like a chore. I felt as though next week had already started. It felt as though I were already burdened with the weights and stresses of the upcoming week.

I played videogames with Forrest and Magnum today - it should have been a fun, enjoyable day.
Instead, I spent almost every moment thinking about how I /should/ be spending my time - preparing for an exam on monday.

Does this end when I graduate? I won't have assignments, I won't have exams, I won't have so many deadlines and due dates as I do now.
But I also won't have as many friends. Here, I'm surrounded by people I know. I have two roomates who, even though they frustrate and irritate me, I enjoy spending time with.
What do I do in a years time when I graduate and suddenly I'm all alone?

I watched two videos today.
[[id:cadf0a39-dedf-4965-8ceb-74f633834a40][Je Te Laisserai Des Mots]] - a cover of such an amazingly beautiful song, using the words to the song as it was originally written.
It emphasizes taking note of the small things. Caring for someone and the small actions that come with that. It's such a sad song, but it perfectly conveys the affection and love that you feel and the deep attatchment you feel for someone that you feel for.

[[id:6304a6a6-8473-4e9c-a13a-7f0989ae516f][The Morning After I Killed Myself]] - a wonderful poem, sad and reflective. Regretful.
The poem is delivered from the point of view of one who has committed suicide, and the morning after, wakes up and sees the beautiful things in the world that they are leaving behind.
The poem ends "The morning after I killed myself, I tried to unkill myself, but couldn't finish what I had started."
There are always parts of our life that seem as though they are going to be the end - the end of happiness, the end of peace, the end of certainty.
Despite that there is always beauty to our lives, and its that beauty that is the reason we are here. 
